name: Mailbox CI

on:
  pull_request:

jobs:
  build-test:
    name: Build and Unit Test Mailbox
    uses: thumperq/cicd/.github/workflows/ci.yaml@v0.1.5
    secrets:
      GITHUBACTION_TOKEN: ${{ secrets.GITHUBACTION_TOKEN }}
      GITHUBACTION_USERNAME: ${{ secrets.GITHUBACTION_USERNAME }}
      DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
