name: Mailbox CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Mailbox
    uses: thumperq/cicd/.github/workflows/cd.yaml@v0.1.36
    secrets:
      ENVIRONMENT: staging
      DOMAIN_NAME: wms
      SERVICE_NAME: mailbox
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ vars.VAULT_TOKEN }}
      # it's in terraform project in the json file
      GCP_CREDENTIALS: ${{ vars.GCP_CREDENTIALS }}
