name: Mailbox CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Mailbox
    uses: thumperq/cicd/.github/workflows/cd.yaml@v0.1.1
    secrets:
      DOCKER_REGISTRY_URL: ${{ vars.DOCKER_REGISTRY_URL }}
      # postgresql://admin_ritgsrtzhz:8ybrlc67xd4ulw6k2jle@10.62.0.3:5432
      DATABASE_INSTANCE_URL: ${{ vars.DATABASE_INSTANCE_URL }}
      # postgresql://admin_ritgsrtzhz:8ybrlc67xd4ulw6k2jle@127.0.0.1:5432
      MIGRATION_DATABASE_INSTANCE_URL: ${{ vars.MIGRATION_DATABASE_INSTANCE_URL }}
      # hoomanfr-domain:us-west1:hoomanfr-domain-20bdb403
      GCP_DB_INSTANCE_NAME: ${{ vars.GCP_DB_INSTANCE_NAME }}
      # mailbox
      DB_NAME: mailbox
      # it's in terraform project in the json file
      GCP_CREDENTIALS: ${{ vars.GCP_CREDENTIALS }}
      # hoomanfr-domain-gke
      GKE_CLUSTER_NAME: ${{ vars.GKE_CLUSTER_NAME }}
      # us-west1-c
      GKE_ZONE: ${{ vars.GKE_ZONE }}
      GITHUBACTION_TOKEN: ${{ vars.GITHUBACTION_TOKEN }}
      # thumperq/cicd
      DEPLOYMENT_REPO: ${{ vars.DEPLOYMENT_REPO }}
      # hoomanfr
      GITHUBACTION_USERNAME: ${{ vars.GITHUBACTION_USERNAME }}
      ENVIRONMENT: staging
      DOMAIN_NAME: wms
      SERVICE_NAME: mailbox
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      # the name under the IP Address in VPC Network with access type external
      GLOBAL_STATIC_IP_NAME: ${{ vars.GLOBAL_STATIC_IP_NAME }}
      # the external ip address on port 8200
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ vars.VAULT_TOKEN }}
